### PR TITLE
fix case insensitive vulnerability

### PR DESCRIPTION
**Pull request by davidyaha**
A recent PR I was urging to merge has brought some nasty loop holes into our mongo driver.. This should fix it

### CODE REVIEW

**Comment by dotansimha** [comment]
Why not use regex? can you explain? @davidyaha

**Comment by davidyaha** [comment]
Take a look on the tests I've added.. using regex it was failing.. we need to sanitize the input if we want to use regex and I feel much more comfortable without using it

**Comment by attritionorg** [comment]
@davidyaha can you confirm the vuln is related to improper handling of usernames (canonicalization issue)?

**Comment by davidyaha** [comment]
@attritionorg I am sorry, I must be missing something. What do you mean vuln?

**Comment by attritionorg** [comment]
@davidyaha The commit title is "fix case insensitive vulnerability". Trying to verify what the vuln(erability) is, sorry for the shorthand!

**Comment by davidyaha** [comment]
Ah okay. So the vulnerability only affects users with mongo driver set to `caseSensitiveUserName: false`. This was recently introduced to this package and the Regex that was added wrongly matched the usernames.
Essentially, including a Regex instance with the supplied username allowed for wrong usage and possible vulnerability in the worst case of just a simple bug with getting the right user object in the best case.
You can take a look at the commits to and see I've added two failing tests for that.

**Pull request merged**
